Imports System.Linq
Imports System.Text
Imports System.Collections.Generic
Imports System

'------------------------------------------------------------------------------
'<auto-generated>
'    This code was generated by a tool.
'    Runtime Version: 16.0.0.0
' 
'    Changes to this file may cause incorrect behavior and will be lost if
'    the code is regenerated.
'</auto-generated>
'------------------------------------------------------------------------------

'''<summary>
'''Class to produce the template output
'''</summary>
<Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")>
    Partial Public Class MyEntityTypeConfigurationGenerator
    Inherits MyCodeGeneratorBase

    '''<summary>
    '''Create the template output
    '''</summary>
    Public Overrides Function TransformText() As String
        Throw New NotImplementedException()
    End Function
End Class
